'use client';

import { useMemo, useState } from 'react';
import { Activity, BarChart3, Brain, ChevronRight, Flame, Goal, Heart, Home, Search, Settings, ShieldCheck, Star, Trophy, X } from 'lucide-react';

type Match = { id:number; home:string; away:string; time:string; league:string; tag:string; score:string; probs:[number,number,number]; btts:number; over:number; confidence:number; xg:[number,number]; form:[string,string]; pick:string };
const matches: Match[] = [
  {id:1,home:'Arsenal',away:'Fulham',time:'20:45',league:'Premier League',tag:'Tippmix',score:'2–0',probs:[69,19,12],btts:48,over:61,confidence:86,xg:[2.04,.81],form:['GY · GY · D · GY · GY','V · D · GY · V · D'],pick:'Hazai győzelem'},
  {id:2,home:'Inter',away:'Torino',time:'21:00',league:'Serie A',tag:'Tippmix',score:'2–0',probs:[72,18,10],btts:41,over:58,confidence:91,xg:[2.19,.69],form:['GY · GY · GY · D · GY','D · V · D · GY · V'],pick:'Over 1.5'},
  {id:3,home:'Dortmund',away:'Mainz',time:'18:30',league:'Bundesliga',tag:'Top liga',score:'2–1',probs:[64,21,15],btts:69,over:70,confidence:78,xg:[1.88,1.21],form:['GY · V · GY · GY · D','D · GY · V · D · GY'],pick:'BTTS – Igen'},
  {id:4,home:'Ferencváros',away:'Paks',time:'19:30',league:'NB I',tag:'Magyar',score:'2–1',probs:[58,24,18],btts:62,over:65,confidence:73,xg:[1.76,1.14],form:['GY · D · GY · GY · V','GY · V · D · GY · D'],pick:'Over 2.5'},
  {id:5,home:'Real Sociedad',away:'Getafe',time:'21:30',league:'La Liga',tag:'Top liga',score:'1–0',probs:[61,27,12],btts:36,over:39,confidence:76,xg:[1.42,.57],form:['D · GY · D · V · GY','V · D · V · D · GY'],pick:'BTTS – Nem'},
];
const nav = [[Home,'Mai meccsek'],[Flame,'Top jelzések'],[Trophy,'Ligák'],[Search,'Meccskereső'],[Brain,'AI modell'],[BarChart3,'Teljesítmény'],[Heart,'Kedvencek'],[Settings,'Beállítások']] as const;

function Confidence({value}:{value:number}){const hot=value>=85;return <span className={`confidence ${hot?'hot':''}`}>{hot?<Flame size={14}/>:<ShieldCheck size={14}/>} {value}</span>}
function MatchCard({match,onOpen}:{match:Match;onOpen:()=>void}){return <article className="match-card"><div className="match-top"><div><span className="time">{match.time}</span><span className="league">{match.league}</span></div><span className="tag"><Star size={12} fill="currentColor"/>{match.tag}</span></div><div className="teams"><strong>{match.home}</strong><span>–</span><strong>{match.away}</strong></div><div className="prediction-row"><div><small>AI várható eredmény</small><b>{match.score}</b></div><div className="probabilities">{['1','X','2'].map((x,i)=><span key={x}><i>{x}</i><b>{match.probs[i]}%</b></span>)}</div></div><div className="market-row"><span>BTTS <b>{match.btts>=50?'IGEN':'NEM'} {match.btts>=50?match.btts:100-match.btts}%</b></span><span>O2.5 <b>{match.over}%</b></span><Confidence value={match.confidence}/></div><button className="detail-btn" onClick={onOpen}>Részletes elemzés <ChevronRight size={16}/></button></article>}

function Detail({match,onClose}:{match:Match;onClose:()=>void}){const matrix=[[5,4,2,1],[11,9,4,1],[14,12,5,2],[10,8,4,1]];return <div className="detail-overlay" role="dialog" aria-modal="true"><div className="detail-panel"><button className="close" onClick={onClose} aria-label="Bezárás"><X/></button><div className="detail-heading"><span>{match.league} · {match.time}</span><h2>{match.home} <em>–</em> {match.away}</h2></div><div className="hero-prediction"><div><small>AI EREDMÉNY-ELŐREJELZÉS</small><strong>{match.score}</strong><p>Várható gól: <b>{match.xg[0].toFixed(2)}</b> – <b>{match.xg[1].toFixed(2)} xG</b></p></div><Confidence value={match.confidence}/></div><div className="detail-grid"><section className="panel"><h3>1X2 valószínűség</h3>{['1 — '+match.home,'X — Döntetlen','2 — '+match.away].map((l,i)=><div className="bar" key={l}><span>{l}</span><div><i style={{width:match.probs[i]+'%'}}/></div><b>{match.probs[i]}%</b></div>)}</section><section className="panel"><h3>Gólpiacok</h3><div className="market-list"><p>Over 1.5 <b>82%</b></p><p>Over 2.5 <b>{match.over}%</b></p><p>Over 3.5 <b>37%</b></p><p>BTTS – Igen <b>{match.btts}%</b></p></div></section><section className="panel wide"><h3>Pontos eredménymátrix</h3><div className="matrix"><div></div>{[0,1,2,3].map(n=><b key={n}>{match.away} {n}</b>)}{matrix.flatMap((row,r)=>[<b key={'r'+r}>{match.home} {r}</b>,...row.map((v,c)=><span className={v>=11?'peak':''} key={r+'-'+c}>{v}%</span>)])}</div><p className="hint">Legvalószínűbb: <b>2–0 (14%)</b> · 2–1 (12%) · 1–0 (11%)</p></section><section className="panel wide reason"><Brain/><div><h3>Miért ezt jósolja az AI?</h3><p>{match.home} hazai támadójátéka stabil, míg {match.away} idegenben átlagosan több helyzetet enged. A Poisson-, Elo-, xG- és formajelzések egyaránt a <b>{match.pick.toLowerCase()}</b> irányába mutatnak. Az 50 000 szimuláció alapján ez a legstabilabb modelljelzés.</p></div></section><section className="panel wide"><h3>Aktuális forma</h3><div className="forms"><p><b>{match.home}</b><span>{match.form[0]}</span></p><p><b>{match.away}</b><span>{match.form[1]}</span></p></div></section></div></div></div>}

export default function HomePage(){const[filter,setFilter]=useState('Összes');const[selected,setSelected]=useState<Match|null>(null);const filtered=useMemo(()=>filter==='Összes'||filter==='Ma'?matches:matches.filter(m=>m.tag===filter||m.league.includes(filter)),[filter]);return <main className="app-shell"><aside className="sidebar"><div className="brand"><div><Activity/></div><span>Match<b>IQ</b></span></div><nav>{nav.map(([Icon,label],i)=><button key={label} className={i===0?'active':''}><Icon size={19}/><span>{label}</span>{i===1&&<i>3</i>}</button>)}</nav><div className="model-status"><span></span><div><b>Modell aktív</b><small>Utolsó frissítés: 08:42</small></div></div></aside><section className="content"><header className="topbar"><div className="mobile-brand"><Activity/><b>MatchIQ</b></div><div className="live"><span/> 24 élő mérkőzés</div><button className="search"><Search size={17}/> Meccs vagy csapat keresése...</button><div className="date-pill">2026. SZEPTEMBER 1. · KEDD</div></header><div className="page"><div className="title-row"><div><p className="eyebrow">NAPI MODELLKÖZPONT</p><h1>Mai mérkőzések</h1><p>Adatvezérelt előrejelzések, frissítve minden nap.</p></div><div className="accuracy"><Goal/><div><small>30 NAPOS PONTOSSÁG</small><b>67,8%</b></div></div></div><div className="filters">{['Összes','Tippmix','Top liga','Magyar','BL/EL','Ma','Holnap'].map(f=><button className={filter===f?'active':''} onClick={()=>setFilter(f)} key={f}>{f}</button>)}</div><section className="signals"><div className="section-heading"><div><Flame/><span><b>Mai legerősebb modelljelzések</b><small>Magas bizalmú, adatvezérelt kiválasztások</small></span></div><p>Nem garantált tippek</p></div><div className="signal-grid">{matches.slice(0,3).map((m,i)=><button onClick={()=>setSelected(m)} className="signal" key={m.id}><span className="rank">0{i+1}</span><div><b>{m.home} – {m.away}</b><small>{m.league} · {m.time}</small></div><span className="pick">{m.pick}</span><strong>{i===1?'82':m.probs[0]}%</strong><Confidence value={m.confidence}/><ChevronRight/></button>)}</div></section><div className="list-heading"><div><h2>Összes mérkőzés</h2><span>{filtered.length} mérkőzés</span></div><small>A megjelenített adatok tesztadatok</small></div><div className="match-grid">{filtered.map(m=><MatchCard key={m.id} match={m} onOpen={()=>setSelected(m)}/>)}</div></div><nav className="mobile-nav">{nav.slice(0,5).map(([Icon,label],i)=><button className={i===0?'active':''} key={label}><Icon/><span>{label.split(' ')[0]}</span></button>)}</nav></section>{selected&&<Detail match={selected} onClose={()=>setSelected(null)}/>}</main>}
